spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demodb
      username: admin
      password: admin123
      authentication-database: admin
    elasticsearch:
      uris: http://localhost:9200
      connection-timeout: 5s
      socket-timeout: 3s

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: TRACE 